### ISSUE TITLE
Remove TaskScheduler::adapter

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/task#12]
While adaption of currently existing promises might seem like a nice migration path, I don't think we should introduce that. If you rewrite your existing code to use `Task::await`, you can probably rewrite it to get rid of promises at the same time. If not, you can use a simple wrapper function to accomplish that. Building that method into the scheduler will result in having the adaption basically forever. Async isn't _very_ widely used yet, I think it's better to concentrate on the future than make existing programs migrate slightly easier.

**Comment by martinschroeder** [comment]
The adapter was just a little idea to make migration of promise-based APIs easier. I do however agree with you that it mind hinder adoption of the task API due to usage of adapter classes. I will remove the adapter feature in #8 because there should be a better way to re-use existing promises.

An idea for such an integration might be to introduce another interface, that can be extended / implemented by promises and does the adapter part. I am thinking of something like `IteratorAggregate` for awaitables, basically like this:

```php
namespace Concurrent;

interface AwaitableAggregate
{
    public function getAwaitable(): Awaitable;
}
```

In `Task::await()` there could be one simple check for that new interface and it would solve the integration part. Every vendor willing to support this could implement the interface and everybody would be ready to go.

**Comment by kelunik** [comment]
I don't think we need any dedicated adapter support. [This](https://github.com/amphp/amp/blob/439516d650495879440aa307fe3e54772fbf6fa3/lib/functions.php#L120-L132) works just fine.
